### PR TITLE
csproj qol improvements

### PR DESCRIPTION
**Pull request by umbravi**
modified csproj to abstract battletech folder location so repo does not need to live with the game files
replaced post build copy script with msbuild targets, debug build copies files, release build creates zip
added common.tasks to allow zipping of files via build task

These are edits to the build process that I made prepping for my own mods using your tooling. Figured I'd share them with you in case you'd like to incorporate them. You'll need to edit < BattleTechDir > in the csproj to reflect your path though.

### CODE REVIEW

**Comment by CptMoore** [comment]
cool difference of release and debug and general use of variables.

ModTek and BTML are using ENV $(BattleTechGame) to identify the games location, is there a way to to have another (gitignored) file that overwrites those settings? So I can set the default to the ENV variable and overwrite that value for myself without modifying any csproject file?

**Comment by CptMoore** [comment]
> `<Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')"/>`

I think that'll do it.

I'll modify stuff a bit and then merge your pr, thx.

**Comment by CptMoore** [comment]
@umbravi  I saw that the project files were still using the old structure only based on BTML. My intention for DynModLib is to be a ModTek mod purely because of dependency management and reuse of mod.json for DLL and namespace naming. Do you want/need a mechanism for DynModLib that doesn't rely on ModTek?

**Comment by umbravi** [comment]
No, I don't. I preserved the structure that existed and is needed currently. It's possible that I misunderstood. My personal, and initial battletechcommon.project move all files into the mod\ (projectname) directory.

**Pull request merged**
